### ISSUE TITLE
Every instance of homebridge creats a button and zone

### ISSUE THREAD

**Issue by iGodPhil** [RandomMetalhead/homebridge-teufel#10]
Hey homebridge automatically creates a button and a zone without being called in config.json. Now I have 8 buttons and zones, because I have 8 instances. You have to improve that urgently. Otherwise this plugin is useless.

**Comment by RandomMetalhead** [comment]
I will have a look on this

**Comment by RandomMetalhead** [comment]
I have created a new version. Could you test? I don´t have a setup like you, so I´m not sure, if it will work... Switches are now based on rooms. At least they should :)

**Comment by iGodPhil** [comment]
Yes i will test it next week but at first I have to rebuild my Homebridge because my sd card crashed last week...

Otherwise i founded a solution for this problem so its not neccessary to fix the problem. In newer Versionen of homebridge you can declare in your config.json which plugin will be loaded in the distance. I can show it next week.

**Comment by iGodPhil** [comment]
So I've tested it now with bad results: 

My frist config.json:

```
{
   "bridge":{
      "name":"Tuya",
      "username":"CC:22:3D:E3:CE:35",
      "port":51831,
      "pin":"031-45-154",
      "model":"Homebridge"
   },
   "accessories":[

   ],
   "platforms":[
      {
         "platform":"config",
         "name":"Config",
         "port":8095,
         "sudo":true,
         "restart":"sudo -n systemctl restart homebridge-tuya",
         "theme":"dark-mode",
         "temp":"/sys/class/thermal/thermal_zone0/temp",
         "log":{
            "method":"systemd",
            "service":"homebridge"
         }
      }
   ]
}
```
 
Homebridge crashed with the following message:

> [2019-9-5 7:42:07 PM] TypeError: Cannot read property 'clearcache' of null
>     at TeufelPlatform.<anonymous> (/usr/lib/node_modules/homebridge-teufel/index.js:42:25)
>     at API.emit (events.js:203:15)
>     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
>     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
>     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> error: uncaughtException: Cannot read property 'clearcache' of null date=Thu Sep 05 2019 19:42:07 GMT+0200 (GMT+02:00), pid=6094, uid=0, gid=0, cwd=/var/lib/homebridge/homebridge-tuya, execPath=/usr/bin/node, version=v10.16.3, argv=[/usr/bin/node, /usr/bin/homebridge, -I, -U, /var/lib/homebridge/homebridge-tuya], rss=92585984, heapTotal=62021632, heapUsed=44847620, external=680163, loadavg=[2.95751953125, 2.3310546875, 1.640625], uptime=971
> TypeError: Cannot read property 'clearcache' of null
>     at TeufelPlatform.<anonymous> (/usr/lib/node_modules/homebridge-teufel/index.js:42:25)
>     at API.emit (events.js:203:15)
>     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
>     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
>     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> [2019-9-5 7:42:07 PM] Homebridge is running on port 51831.
> [2019-9-5 7:42:07 PM] Got SIGTERM, shutting down Homebridge...

This config.json seems to work:

```
{
   "bridge":{
      "name":"Tuya",
      "username":"CC:22:3D:E3:CE:35",
      "port":51831,
      "pin":"031-45-154",
      "model":"Homebridge"
   },
   "plugins":[
      "homebridge-config-ui-x",
      "homebridge-teufel"
   ],
   "accessories":[

   ],
   "platforms":[
      {
         "platform":"config",
         "name":"Config",
         "port":8095,
         "sudo":true,
         "restart":"sudo -n systemctl restart homebridge-tuya",
         "theme":"dark-mode",
         "temp":"/sys/class/thermal/thermal_zone0/temp",
         "log":{
            "method":"systemd",
            "service":"homebridge"
         }
      },
      {
         "platform":"Teufel",
         "name":"Teufel",
         "frozen":false,
         "clearcache":false
      }
   ]
}
```

But if I delete your plugin from the config.json the devices are always in my Homekit App. So I have to delete the whole bridge from Homekit and readd with cleared accessories and persist folders. That sucks.

**Comment by RandomMetalhead** [comment]
Have you used the latest version 0.4.1? And you don’t need to remove the whole bridge. Just delete “accessories” and “persist” folder should be enough.

**Comment by RandomMetalhead** [comment]
But you wrote it works, so I close this issue.

**Comment by iGodPhil** [comment]
No it doesn‘t work as ist should. And of course i have installed the newest Version of your plugin.

If you delete only the accessories and persist folder the connection in HomeKit gets lost to all of your devices so you have to readd the whole bridge. And furthermore if you don’t write your plugin into the config.json but it’s installed the instance of homebridge will crash. I don‘t know why you closed this issue.

For me I have a workaround but what’s up with the other people? Your code has unfortunately  many issues at the moment.

**Comment by RandomMetalhead** [comment]
I don’t build it for the “others” but for me in my spare time. It works fine for me. I gladly help other people if they have issues with my plugin, but you are only complaining. I don’t see you really help solving the issue or contributing any code or help. You just Form other plugins without contributing. Don’t like that...

**Comment by iGodPhil** [comment]
I only want to help you to fix the bugs because I can’t coding. If it is not your intention to fix the bugs we can close the issue. But I think it's a pity for the others. Maybe the log of the error will help you to fix it. 

I have one more question. What does the points clearcache and frozen will do?

The forks are an mistake by me but I don’t know how to delete them from my page.

**Comment by RandomMetalhead** [comment]
Check the readme:

To prevent changing devices to be removed and added again in Homekit, add option 'frozen' = true to config.json. See config-sample.json. This is BETA!
To remove old devices and add new devices, use 'clearcache' = true. This is BETA!

**Comment by RandomMetalhead** [comment]
And from my point of view the bug is fixed. I can not see any problem in the plugin and on my local installation it is working fine. The error you reported looks like you have not installed the latest plugin, because "clearcache" is a new BETA! option, which only exists in the newest version. I have uploaded a new version 4.2. Try this, if it help. 

If you are not willing to test with you homebridge installation, just setup a seconds debug environment, so your real homebridge installation will stay stable...

**Comment by iGodPhil** [comment]
I‘m sorry that I haven‘t read them because I only answering you directly from my mail program.

I‘m not sure what are you meaning because I installed and tested it yesterday? What’s the difference between the newest and latest version? 

I will test it but normally it doesn’t matter how many instances you have because it’s everytime the same. It’s like you open the program more than once. What happens to you when you have installed your plugin but not written in your config.json?

**Comment by RandomMetalhead** [comment]
You need to give you second Homebridge instance another ID in the config.json so you can have multiple instances, not messing with each other. Newest version has some fixed null pointer exceptions, maybe even the one you encountered.

**Comment by iGodPhil** [comment]
I tested the version 0.4.2 with same result. 

> [2019-9-6 4:52:05 PM] TypeError: Cannot read property 'clearcache' of null
>     at TeufelPlatform.<anonymous> (/usr/lib/node_modules/homebridge-teufel/index.js:41:38)
>     at API.emit (events.js:203:15)
>     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
>     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
>     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> error: uncaughtException: Cannot read property 'clearcache' of null date=Fri Sep 06 2019 16:52:05 GMT+0200 (GMT+02:00), pid=2466, uid=0, gid=0, cwd=/var/lib/homebridge/homebridge-tuya, execPath=/usr/bin/node, version=v10.16.3, argv=[/usr/bin/node, /usr/bin/homebridge, -I, -U, /var/lib/homebridge/homebridge-tuya], rss=93065216, heapTotal=61497344, heapUsed=47565264, external=688227, loadavg=[1.35498046875, 2.18505859375, 1.4580078125], uptime=499
> TypeError: Cannot read property 'clearcache' of null
>     at TeufelPlatform.<anonymous> (/usr/lib/node_modules/homebridge-teufel/index.js:41:38)
>     at API.emit (events.js:203:15)
>     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
>     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
>     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> [2019-9-6 4:52:05 PM] Homebridge is running on port 51831.
> [2019-9-6 4:52:05 PM] Got SIGTERM, shutting down Homebridge...

So if you have installed your plugin but its not defined in config.json homebridge will crash. 
I don't think it's a big problem but for people with more than one instance you have define in each instance wich plugin has to load into the plugin chapter like this config.json:

```
{
   "bridge":{
      "name":"Tuya",
      "username":"CC:22:3D:E3:CE:35",
      "port":51831,
      "pin":"031-45-154",
      "model":"Homebridge"
   },
 "plugins":[
      "homebridge-config-ui-x",
      "homebridge-teufel"
   ],
   "accessories":[

   ],
   "platforms":[
      {
         "platform":"config",
         "name":"Config",
         "port":8095,
         "sudo":true,
         "restart":"sudo -n systemctl restart homebridge-tuya",
         "theme":"dark-mode",
         "temp":"/sys/class/thermal/thermal_zone0/temp",
         "log":{
            "method":"systemd",
            "service":"homebridge"
         }
      },
      {
         "platform":"Teufel",
         "name":"Teufel",
         "frozen":false,
         "clearcache":false
      }
   ]
}
```

**Comment by iGodPhil** [comment]
And I don't know why you don't have this problem. It makes no sense for me because every instance of mine works well. Thats not the problem. 

So you have tested it like me if you have installed your plugin but it's not defined in config.json?
