### ISSUE TITLE
Running in Docker - Permission Denied when writing log

### ISSUE THREAD

**Issue by mab2k** [RandomMetalhead/homebridge-teufel#9]
Logs should go to HOMEBRIDGE_HOME/logs and not the fs-root.

[3/3/2019, 4:14:00 PM] Homebridge is running on port 51826.
info: [Raumkernel] Found raumfeld host on: 192.168.178.23
error: uncaughtException: EACCES: permission denied, open '/app.2019-03-03-1514.log' date=Sun Mar 03 2019 16:14:00 GMT+0100 (Central European Standard Time), pid=21438, uid=1025, gid=100, cwd=/run/s6/services/homebridge, execPath=/usr/local/bin/node, version=v10.15.1, argv=[/usr/local/bin/node, /usr/local/bin/homebridge, -U, /homebridge, -P, /homebridge/node_modules, -C], rss=70402048, heapTotal=39055360, heapUsed=21550552, external=948049, loadavg=[0.55419921875, 0.35986328125, 0.21484375], uptime=397809
Error: EACCES: permission denied, open '/app.2019-03-03-1514.log'

**Comment by RandomMetalhead** [comment]
Hi mab2k, this error message seems to come from "Raumkernel" itself. I will have a look into it.

**Comment by RandomMetalhead** [comment]
Hi @mab2k, the issue should be gone now with version 0.3.5. Could you please check?
